# Generated by Django 3.0.5 on 2020-04-12 05:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_name', models.CharField(max_length=100)),
                ('pizza_description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('pizza_image', models.ImageField(upload_to='pizza_pics')),
                ('pizza_choice', models.CharField(choices=[('Veg', 'Veg Pizza'), ('Non-Veg', 'Non-Veg Pizza'), ('Jain', 'Veg Pizza for Jains')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('desc', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_price', models.IntegerField()),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('bill_name', models.CharField(max_length=100)),
                ('bill_mob', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('bill_state', models.CharField(max_length=50)),
                ('bill_city', models.CharField(max_length=50)),
                ('bill_add', models.CharField(max_length=200)),
                ('extra', models.ManyToManyField(blank=True, to='order.Toppings')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Pizza')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
