# Generated by Django 3.0.5 on 2020-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_out',
            name='limit',
        ),
        migrations.AddField(
            model_name='time_out',
            name='limit_minutes',
            field=models.IntegerField(default=10),
        ),
    ]
