# Generated by Django 3.0.5 on 2020-04-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200412_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='updateable',
            field=models.IntegerField(default=120),
        ),
    ]
