# Generated by Django 3.0.5 on 2020-04-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orders_updateable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='updateable',
            field=models.IntegerField(),
        ),
    ]
