# Generated by Django 3.0.5 on 2020-04-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20200412_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='pizza_choice',
            new_name='pizza_category',
        ),
    ]
